baseURL = "https://marcobacis.com/"
languageCode = "en-uk"
title = "Marco Bacis"
theme = "mediumish-gohugo-theme"
copyright = "Â© Copyright Marco Bacis 2018-{year}"
googleAnalytics = "G-WJJS43TXKN"
disqusShortname = "marcobacis-1"

enableGitInfo = true

[params.index]
  picture = "/images/avatar.svg"
  title = "Hello!"
  subtitle = "I'm Marco, an Italian software engineer based in Milan"
  mdtext = ''''''
  alertbar = true

[params.author]
  name = "Marco Bacis"
  thumbnail = "/images/avatar_real.webp"
  description = "Software Engineer / Tinkerer"

[params.social]
  github = "marcobacis"
  linkedin = "marcobacis"
  medium = "marcobacis"
  twitter = "marcbacis"

[params]
  description= "The personal website of Marco Bacis, a passionate Software Engineer from Italy" 

## Main Menu
[[menu.main]]
    name = "Home"
    weight = 50
    identifier = ""
    url = "/"
[[menu.main]]
    name = "Now"
    weight = 60
    identifier = "now"
    url = "/now"
[[menu.main]]
    name = "Blog"
    weight = 70
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Projects"
    weight = 100
    identifier = "projects"
    url = "/projects"
[[menu.main]]
    name = "Publications"
    weight = 150
    identifier = "publications"
    url = "/publications"
[[menu.main]]
    name = "CV"
    weight = 200
    identifier = "curriculum"
    url = "/cv"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about"