baseURL = "http://marcobacis.com/"
languageCode = "en-us"
title = "Marco Bacis"
theme = "mediumish-gohugo-theme"


[params.index]
  picture = "/images/marco.jpg"
  title = "Hello!"
  subtitle = "I'm Marco, an Italian software engineer based in Milan"
  mdtext = ''''''
  alertbar = true

[params.author]
  name = "Marco Bacis"
  thumbnail = "/images/marco.jpg"
  description = "<insert description here>"

[params.social]
  github = "marcobacis"
  linkedin = "marcobacis"
  medium = "marcobacis"
  twitter = "marcbacis"


## Main Menu
[[menu.main]]
    name = "ğŸ  Home"
    weight = 50
    identifier = ""
    url = "/"
[[menu.main]]
    name = "ğŸ›  Projects"
    weight = 100
    identifier = "projects"
    url = "/projects"
[[menu.main]]
    name = "ğŸ“œ Publications"
    weight = 150
    identifier = "publications"
    url = "/publications"
[[menu.main]]
    name = "ğŸ’¼ CV"
    weight = 200
    identifier = "curriculum"
    url = "/cv"
[[menu.main]]
    name = "â„¹ï¸ About"
    identifier = "about"
    weight = 300
    url = "/about"